Update your Description
DevSpaceHuntsville/WebsiteAndApi pull request #71
Opened 2020-09-30 14:39 UTC by SauravMiah

- Please submit all pull requests to branch staging (not master)

2020-09-30 15:20 UTC, ProfessorTom requested changes

2020-09-30 15:20 UTC, ProfessorTom commented on README.md
> +This is the bestwebsite used for the DevSpace Technical Conference in Huntsville, Alabama.
add a space between `best` and `website`, please

2020-09-30 15:24 UTC, freestylecoder requested changes

2020-09-30 15:24 UTC, freestylecoder commented on README.md
> +This is the bestwebsite used for the DevSpace Technical Conference in Huntsville, Alabama.
This really isn't the "best" website. Buttering up the reviewer will do you nothing. Please remove.

2020-09-30 15:24 UTC, freestylecoder commented on README.md
> +The staging website uses a backup of the production database. The production database is copied to the staging database at about 3am every day. If you want to see how that happens, look at the devspa
AM is correct. However, there should technically be a space between 3 and AM.  So, I'm more than happy to approve your pull request, but it should be "3 AM" and not "3am".

2020-10-02 14:08 UTC, freestylecoder commented
I gave a reasonable amount of time for this to be tweaked. Closed as Hacktoberfest spam.

2020-10-02 14:08 UTC, closed without merging